apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.ke.roleBinding.name }}
  namespace: {{ .Values.ke.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.ke.role.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.ke.serviceAccount.name }}
    namespace: {{ .Values.ke.namespace }}