apiVersion: v1
kind: Service
metadata:
  labels:
    role: {{ include "kube-enforcer.fullname" . }}
  name: {{ include "kube-enforcer.fullname" . }}
  namespace: {{ .Values.ke.namespace }}
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: {{ include "kube-enforcer.fullname" . }}